name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Replace API Key
        run: sed -i 's/\${API_KEY}/${{ secrets.OPENWEATHERMAP_API_KEY }}/g' index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1