name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace API Key
        run: |
          echo "Replacing API key..."
          export API_KEY="${{ secrets.OPENWEATHERMAP_API_KEY }}"
          envsubst < index.html > index_replaced.html
          mv index_replaced.html index.html

      - name: Debug Files
        run: ls -R

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
